export const ErrorCodes = {
    // ========================
    // AUTH-SPD
    // ========================

    INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
    USER_INACTIVE: "USER_INACTIVE",
    EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",
    EMAIL_ALREADY_VERIFIED: "EMAIL_ALREADY_VERIFIED",
    EMAIL_ALREADY_REGISTERED: "EMAIL_ALREADY_REGISTERED",
    USER_NOT_FOUND: "USER_NOT_FOUND",
    INVALID_VERIFICATION_CODE: "INVALID_VERIFICATION_CODE",
    INVALID_PASSWORD: "INVALID_PASSWORD", // NOSONAR — error code label, not a credential
    EMAIL_NOT_VERIFIED_FOR_RESET: "EMAIL_NOT_VERIFIED_FOR_RESET",
    INVALID_RESET_CODE: "INVALID_RESET_CODE",

    INVALID_REFRESH_TOKEN: "INVALID_REFRESH_TOKEN",
    REFRESH_TOKEN_REVOKED: "REFRESH_TOKEN_REVOKED",

    ROLE_NOT_FOUND: "ROLE_NOT_FOUND",
    ROLE_ALREADY_ASSIGNED: "ROLE_ALREADY_ASSIGNED",
    ROLE_NOT_ASSIGNED: "ROLE_NOT_ASSIGNED",
    ROLE_ALREADY_EXISTS: "ROLE_ALREADY_EXISTS",
    ROLE_HAS_USERS: "ROLE_HAS_USERS",

    MODULE_NOT_FOUND: "MODULE_NOT_FOUND",
    MODULE_ALREADY_EXISTS: "MODULE_ALREADY_EXISTS",
    MODULE_PUBLIC_CANNOT_MODIFY: "MODULE_PUBLIC_CANNOT_MODIFY",
    MODULE_PUBLIC_CANNOT_DELETE: "MODULE_PUBLIC_CANNOT_DELETE",

    ACTION_NOT_FOUND: "ACTION_NOT_FOUND",
    ACTION_ALREADY_EXISTS: "ACTION_ALREADY_EXISTS",

    PERMISSION_NOT_FOUND: "PERMISSION_NOT_FOUND",
    PERMISSION_ALREADY_EXISTS: "PERMISSION_ALREADY_EXISTS",

    EMAIL_IN_USE: "EMAIL_IN_USE",
    DOCUMENT_IN_USE: "DOCUMENT_IN_USE",
    DOCUMENT_ALREADY_REGISTERED: "DOCUMENT_ALREADY_REGISTERED",
    DEFAULT_ROLE_NOT_FOUND: "DEFAULT_ROLE_NOT_FOUND",
    NOT_REGISTERED_IN_SYSTEM: "NOT_REGISTERED_IN_SYSTEM",
    CANNOT_REMOVE_LAST_ROLE: "CANNOT_REMOVE_LAST_ROLE",

    FORBIDDEN: "FORBIDDEN",
    NO_ACTIVE_ROLE: "NO_ACTIVE_ROLE",

    // ========================
    // SPD-CORE — MASTERS
    // ========================

    // Variables
    VARIABLE_NOT_FOUND: "VARIABLE_NOT_FOUND",
    VARIABLE_CODE_ALREADY_EXISTS: "VARIABLE_CODE_ALREADY_EXISTS",
    VARIABLE_HAS_RELATIONS: "VARIABLE_HAS_RELATIONS",

    // Variable Ubicaciones
    VARIABLE_LOCATION_ALREADY_EXISTS: "VARIABLE_LOCATION_ALREADY_EXISTS",
    VARIABLE_LOCATION_NOT_FOUND: "VARIABLE_LOCATION_NOT_FOUND",

    // Metas de Variable
    VARIABLE_GOAL_NOT_FOUND: "VARIABLE_GOAL_NOT_FOUND",
    VARIABLE_GOAL_ALREADY_EXISTS: "VARIABLE_GOAL_ALREADY_EXISTS",

    // Cuatrienios de Variable
    VARIABLE_QUADRENNIUM_NOT_FOUND: "VARIABLE_QUADRENNIUM_NOT_FOUND",
    VARIABLE_QUADRENNIUM_INVALID_RANGE: "VARIABLE_QUADRENNIUM_INVALID_RANGE",

    // Ubicaciones
    LOCATION_NOT_FOUND: "LOCATION_NOT_FOUND",

    // Actividades MGA
    MGA_ACTIVITY_NOT_FOUND: "MGA_ACTIVITY_NOT_FOUND",
    MGA_ACTIVITY_CODE_ALREADY_EXISTS: "MGA_ACTIVITY_CODE_ALREADY_EXISTS",
    MGA_DETAILED_RELATION_ALREADY_EXISTS: "MGA_DETAILED_RELATION_ALREADY_EXISTS",
    MGA_DETAILED_RELATION_NOT_FOUND: "MGA_DETAILED_RELATION_NOT_FOUND",

    // Actividades Detalladas
    DETAILED_ACTIVITY_NOT_FOUND: "DETAILED_ACTIVITY_NOT_FOUND",
    DETAILED_ACTIVITY_HAS_RELATIONS: "DETAILED_ACTIVITY_HAS_RELATIONS",

    // Modificaciones Presupuestales
    BUDGET_MODIFICATION_INVALID_TYPE: "BUDGET_MODIFICATION_INVALID_TYPE",
    BUDGET_MODIFICATION_INSUFFICIENT_BALANCE: "BUDGET_MODIFICATION_INSUFFICIENT_BALANCE",
    BUDGET_MODIFICATION_SOURCE_NOT_FOUND: "BUDGET_MODIFICATION_SOURCE_NOT_FOUND",
    BUDGET_MODIFICATION_TARGET_NOT_FOUND: "BUDGET_MODIFICATION_TARGET_NOT_FOUND",

    // Fórmulas
    FORMULA_NOT_FOUND: "FORMULA_NOT_FOUND",
    FORMULA_INVALID_AST: "FORMULA_INVALID_AST",

    // Indicadores Plan de Acción
    ACTION_INDICATOR_NOT_FOUND: "ACTION_INDICATOR_NOT_FOUND",
    ACTION_INDICATOR_CODE_ALREADY_EXISTS: "ACTION_INDICATOR_CODE_ALREADY_EXISTS",
    ACTION_INDICATOR_GOAL_NOT_FOUND: "ACTION_INDICATOR_GOAL_NOT_FOUND",
    ACTION_INDICATOR_QUADRENNIUM_NOT_FOUND: "ACTION_INDICATOR_QUADRENNIUM_NOT_FOUND",
    ACTION_INDICATOR_LOCATION_ALREADY_EXISTS: "ACTION_INDICATOR_LOCATION_ALREADY_EXISTS",
    ACTION_INDICATOR_LOCATION_NOT_FOUND: "ACTION_INDICATOR_LOCATION_NOT_FOUND",

    // Relaciones Variable/Proyecto ↔ Indicador Plan de Acción
    VARIABLE_ACTION_RELATION_ALREADY_EXISTS: "VARIABLE_ACTION_RELATION_ALREADY_EXISTS",
    VARIABLE_ACTION_RELATION_NOT_FOUND: "VARIABLE_ACTION_RELATION_NOT_FOUND",
    PROJECT_ACTION_RELATION_ALREADY_EXISTS: "PROJECT_ACTION_RELATION_ALREADY_EXISTS",
    PROJECT_ACTION_RELATION_NOT_FOUND: "PROJECT_ACTION_RELATION_NOT_FOUND",

    // Indicadores Plan Indicativo
    INDICATIVE_INDICATOR_NOT_FOUND: "INDICATIVE_INDICATOR_NOT_FOUND",
    INDICATIVE_INDICATOR_CODE_ALREADY_EXISTS: "INDICATIVE_INDICATOR_CODE_ALREADY_EXISTS",
    INDICATIVE_INDICATOR_GOAL_NOT_FOUND: "INDICATIVE_INDICATOR_GOAL_NOT_FOUND",
    INDICATIVE_INDICATOR_QUADRENNIUM_NOT_FOUND: "INDICATIVE_INDICATOR_QUADRENNIUM_NOT_FOUND",
    INDICATIVE_INDICATOR_LOCATION_ALREADY_EXISTS: "INDICATIVE_INDICATOR_LOCATION_ALREADY_EXISTS",
    INDICATIVE_INDICATOR_LOCATION_NOT_FOUND: "INDICATIVE_INDICATOR_LOCATION_NOT_FOUND",

    // Relaciones Variable ↔ Indicador Plan Indicativo
    VARIABLE_INDICATIVE_RELATION_ALREADY_EXISTS: "VARIABLE_INDICATIVE_RELATION_ALREADY_EXISTS",
    VARIABLE_INDICATIVE_RELATION_NOT_FOUND: "VARIABLE_INDICATIVE_RELATION_NOT_FOUND",

    // ========================
    // SPD-CORE — FINANCIAL
    // ========================

    // Proyectos
    PROJECT_NOT_FOUND: "PROJECT_NOT_FOUND",
    PROJECT_CODE_ALREADY_EXISTS: "PROJECT_CODE_ALREADY_EXISTS",
    PROJECT_DEPENDENCY_NOT_FOUND: "PROJECT_DEPENDENCY_NOT_FOUND",

    // Fuentes de Financiación
    FUNDING_SOURCE_NOT_FOUND: "FUNDING_SOURCE_NOT_FOUND",
    FUNDING_SOURCE_CODE_ALREADY_EXISTS: "FUNDING_SOURCE_CODE_ALREADY_EXISTS",
    FUNDING_SOURCE_HAS_RELATIONS: "FUNDING_SOURCE_HAS_RELATIONS",

    // POAI-PPA
    POAI_PPA_NOT_FOUND: "POAI_PPA_NOT_FOUND",
    POAI_PPA_ALREADY_EXISTS: "POAI_PPA_ALREADY_EXISTS",

    // CDP
    CDP_NOT_FOUND: "CDP_NOT_FOUND",
    CDP_POSITION_NOT_FOUND: "CDP_POSITION_NOT_FOUND",
    CDP_POSITION_ACTIVITY_ALREADY_ASSOCIATED: "CDP_POSITION_ACTIVITY_ALREADY_ASSOCIATED",
    CDP_POSITION_ACTIVITY_NOT_ASSOCIATED: "CDP_POSITION_ACTIVITY_NOT_ASSOCIATED",

    // CDP Financiamiento
    CDP_FUNDING_INSUFFICIENT_BALANCE: "CDP_FUNDING_INSUFFICIENT_BALANCE",
    CDP_FUNDING_INVALID_AMOUNT: "CDP_FUNDING_INVALID_AMOUNT",

    // Dependencias
    DEPENDENCY_NOT_FOUND: "DEPENDENCY_NOT_FOUND",

    // Necesidades
    NEED_NOT_FOUND: "NEED_NOT_FOUND",

    // ========================
    // SPD-CORE — SUB (Seguimiento)
    // ========================

    // Avances de Variable
    VARIABLE_ADVANCE_NOT_FOUND: "VARIABLE_ADVANCE_NOT_FOUND",
    VARIABLE_ADVANCE_ALREADY_EXISTS: "VARIABLE_ADVANCE_ALREADY_EXISTS",
    VARIABLE_ADVANCE_VARIABLE_NOT_FOUND: "VARIABLE_ADVANCE_VARIABLE_NOT_FOUND",

    // Avances de Indicador
    INDICATOR_ADVANCE_NOT_FOUND: "INDICATOR_ADVANCE_NOT_FOUND",

    // Evaluación de Fórmulas
    FORMULA_EVALUATION_ERROR: "FORMULA_EVALUATION_ERROR",
    FORMULA_DIVISION_BY_ZERO: "FORMULA_DIVISION_BY_ZERO",

    // ========================
    // SPD-CORE — SAP SYNC
    // ========================

    SAP_SYNC_FAILED: "SAP_SYNC_FAILED",
    SAP_API_ERROR: "SAP_API_ERROR",
    SAP_PARSE_ERROR: "SAP_PARSE_ERROR",
} as const;

export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes];
