export const ErrorCodes = {
    INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
    USER_INACTIVE: "USER_INACTIVE",
    EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",
    EMAIL_ALREADY_VERIFIED: "EMAIL_ALREADY_VERIFIED",
    EMAIL_ALREADY_REGISTERED: "EMAIL_ALREADY_REGISTERED",
    USER_NOT_FOUND: "USER_NOT_FOUND",
    INVALID_VERIFICATION_CODE: "INVALID_VERIFICATION_CODE",
    INVALID_PASSWORD: "INVALID_PASSWORD",
    EMAIL_NOT_VERIFIED_FOR_RESET: "EMAIL_NOT_VERIFIED_FOR_RESET",
    INVALID_RESET_CODE: "INVALID_RESET_CODE",

    INVALID_REFRESH_TOKEN: "INVALID_REFRESH_TOKEN",
    REFRESH_TOKEN_REVOKED: "REFRESH_TOKEN_REVOKED",

    ROLE_NOT_FOUND: "ROLE_NOT_FOUND",
    ROLE_ALREADY_ASSIGNED: "ROLE_ALREADY_ASSIGNED",
    ROLE_NOT_ASSIGNED: "ROLE_NOT_ASSIGNED",
    ROLE_ALREADY_EXISTS: "ROLE_ALREADY_EXISTS",
    ROLE_HAS_USERS: "ROLE_HAS_USERS",

    MODULE_NOT_FOUND: "MODULE_NOT_FOUND",
    MODULE_ALREADY_EXISTS: "MODULE_ALREADY_EXISTS",

    ACTION_NOT_FOUND: "ACTION_NOT_FOUND",
    ACTION_ALREADY_EXISTS: "ACTION_ALREADY_EXISTS",

    PERMISSION_NOT_FOUND: "PERMISSION_NOT_FOUND",
    PERMISSION_ALREADY_EXISTS: "PERMISSION_ALREADY_EXISTS",

    EMAIL_IN_USE: "EMAIL_IN_USE",
    DOCUMENT_IN_USE: "DOCUMENT_IN_USE",
    DOCUMENT_ALREADY_REGISTERED: "DOCUMENT_ALREADY_REGISTERED",
    DEFAULT_ROLE_NOT_FOUND: "DEFAULT_ROLE_NOT_FOUND",
    NOT_REGISTERED_IN_SYSTEM: "NOT_REGISTERED_IN_SYSTEM",
    CANNOT_REMOVE_LAST_ROLE: "CANNOT_REMOVE_LAST_ROLE",
} as const;

export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes];
